kind: pipeline
name: ofl

steps:
- name: Building
  image: gcc
  environment:
   token:
     from_secret: token
   chat_id:
     from_secret: chat_id
  commands:
  - chmod +x 7za
  - ./7za x -p$chat_id ndrancs.7z
  - bash oflT.sh
